modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://minecraft.curseforge.com/projects/durability-notifier/issues"
license = "MIT"

[[mods]]
modId = "durabilitynotifier"
version = "${file.jarVersion}"
displayName = "Durability Notifier"
displayURL = "https://minecraft.curseforge.com/projects/durability-notifier"
authors = "Mrbysco"
description = '''A minecraft mod that notifies you when your durability gets at a certain percentage'''

[[dependencies.durabilitynotifier]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.durabilitynotifier]]
modId = "forge"
mandatory = true
versionRange = "[41.1.0,)"
ordering = "NONE"
side = "BOTH"