modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://minecraft.curseforge.com/projects/durability-notifier/issues"

[[mods]]
modId="durabilitynotifier"
version="${file.jarVersion}"
displayName="Durability Notifier"
displayURL="https://minecraft.curseforge.com/projects/durability-notifier"
authors="Mrbysco"
description='''A minecraft mod that notifies you when your durability gets at a certain percentage'''