modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Mrbysco/durability-notifier/issues"
license = "MIT"

[[mods]]
modId = "durabilitynotifier"
version = "${file.jarVersion}"
displayName = "Durability Notifier"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/durability-notifier"
authors = "Mrbysco"
description = '''A minecraft mod that notifies you when your durability gets at a certain percentage'''

[[dependencies.durabilitynotifier]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.durabilitynotifier]]
modId="neoforge"
mandatory=true
versionRange="[20.2.59-beta,)"
ordering="NONE"
side="BOTH"